import sys
import csv

'''
    You will only be writing code in this file and this is the only file submitted to the autograder.
'''

def get_version():
    '''
        print the version of python that you are using.
    '''
    "*** WRITE YOUR CODE HERE ***"
    temp = sys.version
    temp = temp[0:5]
    return temp

def alternative_sum(start, n):
    '''
        modify the function to return a list with generated by an alternative sum sequence explained in the assignment handout
    '''
    "*** WRITE YOUR CODE HERE ***"
    ret_list = []
    if (start < 0):
        return ret_list
    if (start == 0):
        return ret_list.append(start)
    if (n < 5 or n > 20):
        return ret_list
    ret_list.append(start) 
    for num in range(n-1):
        if num == 0:
            ret_list.append(start + start)
        elif num == 1:
            ret_list.append(ret_list[num]*2)
        else:
            ret_list.append(ret_list[num] + ret_list[num-2])
    return ret_list

def order_scores():
    '''
        read the files scores.csv in the data directory and return the list of names sorted in ascending order of the scores.
    '''
    "*** WRITE YOUR CODE HERE ***"
    name_list = {}
    with open("data/scores.csv", "r") as f:
        names = csv.DictReader (f)   
        for line in names:
            name_list[line['name']] = int(line['scores'])           
        else:
            f.close()
    name_list = sorted (name_list, key=name_list.__getitem__)
    return name_list
